-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME,FAVORITES 
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES)  FROM REST_INFO
  GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;

# 음식 종류별 / 즐결찾기 가장 많은 식당 
# 음식 종류기준 내림차순