-- 코드를 입력하세요
-- 고양이 개 각 갯수 
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) as count
FROM ANIMAL_INS
WHERE ANIMAL_TYPE IN ('DOG', 'CAT')
GROUP BY ANIMAL_TYPE
ORDER BY CASE 
    WHEN ANIMAL_TYPE = 'Cat' THEN 1
    WHEN ANIMAL_TYPE = 'Dog' THEN 2
    ELSE 3
END;